core/log.py
lib/graph/d3_tree_v1/engine.py
lib/html_log/_log_data.py

i set text align of table cells to center .
also improved `d3_tree_v1` :
- make footer size smaller and bring it center
- bring header title and description to center
i didn't changed a lot .if it was ok i will work more on it . 
**OS**: `Ubuntu `
**Python Version**: `3.6.3`

improve html report

---

core/ip.py
core/targets.py
lib/scan/dir/engine.py
lib/scan/subdomain/engine.py
lib/scan/tcp_connect_port/engine.py
lib/scan/viewdns_reverse_ip_lookup/engine.py

added support of single IPv6 in all the scans
currently working on expanding range ipv6 and CIDR ipv6
**OS**: `windows`
**OS Version**: `windows 10`
**Python Version**: `3.6`

added single ipv6 support

---

core/log.py

bad operand type has been fixed.
**OS**: `MacOS`
**OS Version**: `High Sierra`
**Python Version**: `2.7.01`

fix bad operand type error

---

setup.py

Hello,
setup.py has been fixed for issue #29 
Regards.
**OS**: `MacOS`
**OS Version**: `High Sierra`
**Python Version**: `2.7.01`

add tmp and results

---

core/config.py
core/config_builder.py
core/load_modules.py
core/parse.py
lib/brute/ftp/engine.py
lib/brute/smtp/engine.py
lib/brute/ssh/engine.py
lib/scan/dir/engine.py
lib/scan/pma/engine.py
lib/scan/subdomain/engine.py
lib/scan/tcp_connect_port/engine.py
lib/vuln/heartbleed/engine.py

Hello everyone,
filepath function has been added for issue #34
Regards.
**OS**: `MacOS`-`Ubuntu`
**OS Version**: `High Sierra`
**Python Version**: `2.7.01`

Add filepath func

---

lib/scan/dir/engine.py
lib/scan/pma/engine.py

update the dev branch

---

api/__start_scan.py
api/api_core.py
core/args_loader.py
core/attack.py
core/config.py
core/config_builder.py
core/parse.py
lib/brute/ftp/engine.py
lib/brute/smtp/engine.py
lib/brute/ssh/engine.py
lib/language/messages_en.py
lib/scan/dir/engine.py
lib/scan/pma/engine.py
lib/scan/port/engine.py
lib/vuln/heartbleed/engine.py
lib/vuln/wordpress_dos_cve_2018_6389/engine.py

Hello,
updating master from dev branch which contains remove unnecessary variables and remove multiprocess option in CLI and API.
Regards.

optimze engine

---

lib/scan/pma/engine.py

This PR is in reference to the issue #44.

Fixes multiple import issue in pma_scan

---

lib/language/messages_en.py
lib/scan/icmp/__init__.py
lib/scan/icmp/engine.py

This PR implements the icmp scan module in reference to #12. Looking forward to your feedback!

Add icmp_scan module

---

lib/brute/ftp/engine.py
lib/brute/smtp/engine.py
lib/brute/ssh/engine.py
lib/scan/dir/engine.py
lib/scan/port/engine.py
lib/scan/subdomain/engine.py
lib/vuln/heartbleed/engine.py
lib/vuln/wordpress_dos_cve_2018_6389/engine.py

Fixes issue #48

---

lib/brute/telnet/__init__.py
lib/brute/telnet/engine.py
lib/language/messages_en.py

This PR adds the telnet brute force module in reference to issue #12. Please review the PR and let me know about any changes.

Add telnet_brute module

---

readme.md

Update readme to include newer methods

---

lib/language/messages_en.py
lib/scan/wappalyzer/__init__.py
lib/scan/wappalyzer/apps.json
lib/scan/wappalyzer/engine.py

This is in reference to #12. This PR implements http wappalyzer scan.

Adds wappalyzer scan module

---

core/targets.py
lib/brute/http_basic_auth/engine.py

Fixes Issue#74

---

lib/brute/http_basic_auth/engine.py
lib/brute/http_form/engine.py
lib/brute/http_ntlm/engine.py
lib/language/messages_en.py

This PR is to update the http brute modules to handle cases when no auth is avaliable

Handle case when no auth

---

lib/scan/port/engine.py

**OS**: `Linux`
**OS Version**: `Ubuntu`
**Python Version**: `2.7.3`

Update port_scan engine.py #83

---

lib/vuln/content_security_policy/__init__.py
lib/vuln/content_security_policy/engine.py

**OS**: `Linux`
**OS Version**: `Ubuntu`
**Python Version**: `2.7.3`

content Security policy Vuln

---

api/__database.py
api/api_core.py
web/static/index.html
web/static/js/main.js

This PR mainly fixes some UI bugs:
* The search result in the crawler on clicking on next page showed all results.
* For the first page now, the previous button is hidden and on end of results it shows no more results.
* The respective tags for the scan and the others were made of the same color.
Please review and let me know about any changes.
Regards.
**Browser**: `Firefox`

Minor UI bug fixes

---

api/api_core.py
core/config.py

Please review the PR and let me know the changes.
**OS Version**: `16.04`
**Web Browser**: `Firefox`

Resolves Issue#103

---

readme.md

Update the new link in readme
**OS Version**: `16.04`

Update the new link in readme

---

lib/scan/port/engine.py
lib/vuln/apache_struts/engine.py

**OS**: `x`
**OS Version**: `x`
**Python Version**: `x`

HTTPS Target Type & Stealth Scan

---

core/targets.py

…gnized by nettacker correctoly.
**OS**: 'Linux' or 'Windows'
**OS Version**: `x`

Now http://website.com  as well as http://website.com/  both are recognized by nettacker correctoly and no error comes.

---

requirements.txt
setup.py

Solve #130 
**OS Version**: `16.04`
**Python Version**: `2.7.4`

Solve python2 and python3 requirements

---

PULL_REQUEST_TEMPLATE.md

This changes the pull request template.
**OS Version**: `16.04`

Change the pull request template

---

lib/scan/joomla_user_enum/__init__.py
lib/scan/joomla_user_enum/engine.py

Joomla Username Enumeration scan using feed
**OS Version**: `14.04`
**Python Version**: `2.7.3`

Joomla username enumeration Scan

---

lib/scan/port/engine.py

- [YES] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [YES] I have added the relevant documentation.
- [YES] My branch is up-to-date with the Upstream master branch.
Added service with port
- OS: `Ubuntu`
- OS Version: `14.04`

Added service names in port scan

---

core/attack.py
requirements.txt

Resolved #141  Insecure Requests Warning message
Resolved #139  Ipaddr not found or required
- OS: `Debian`
- OS Version: `Kali Linux`

Resolved issue #141 and #139

---

lib/scan/wappalyzer/engine.py

This resolves issue #111 
- OS: `Ubuntu`
- Python Version: `2.7`

Resolves Issue #111

---

core/attack.py
lib/payload/scanner/service/engine.py
lib/vuln/xdebug_rce/__init__.py
lib/vuln/xdebug_rce/engine.py
requirements.txt

Added Xdebug vuln module and added service scanners signatures
- OS: `x`

Added Xdebug vuln module and added service scanners signatures

---

lib/scan/port/engine.py

Added UDP port scan using python socket and added UDP service names using python socket module
- OS: `Kali Linux`
- OS Version: `2.0`

UDP Port scan with service names

---

lib/payload/scanner/service/engine.py
lib/scan/port/engine.py
lib/scan/wordpress_version/engine.py

Added Service Scanner signatures for:
PostgreSQL
PortMap
PPTP
Rsync
RTSP
ILC 150 GSM/GPRS (Pcworx)
Added New info for Wordpress version
- OS: `Kali linux`
- OS Version: `2.0`

Added Service Scanner signatures and new info for wordpress version

---

requirements.txt
setup.py

Bug fix #158 
- OS: `Kali Linux`
- OS Version: `2.0`

Bug Fix setup.py

---

CONTRIBUTING.md
lib/graph/d3_tree_v1/engine.py
lib/graph/jit_circle_v1/engine.py
lib/language/messages_ar.py
lib/language/messages_de.py
lib/language/messages_el.py
lib/language/messages_en.py
lib/language/messages_es.py
lib/language/messages_fa.py
lib/language/messages_fr.py
lib/language/messages_hi.py
lib/language/messages_hy.py
lib/language/messages_id.py
lib/language/messages_it.py
lib/language/messages_iw.py
lib/language/messages_ja.py
lib/language/messages_ko.py
lib/language/messages_nl.py
lib/language/messages_ps.py
lib/language/messages_ru.py
lib/language/messages_tr.py
lib/language/messages_ur.py
lib/language/messages_vi.py
lib/language/messages_zh-cn.py
lib/payload/shellcode/readme.md
lib/vuln/wordpress_dos_cve_2018_6389/engine.py
readme.md
setup.py
web/static/index.html

I have replaced most of the viraintel occurences with zdresearch.
- OS: `Ubuntu`

Replace viraintel with zdresearch

---

core/log.py
database/db.py
lib/language/messages_en.py

This solves issue #165. I have checked if the log is JSON or not. If it is not JSON, I have displayed a warning in the terminal. We can do away with the warning also but I am not sure if that is the right way. Please review the PR.
- OS: `Ubuntu`

Solve issue#165

---

lib/payload/scanner/service/engine.py

I have added some more signatures to the service scanner and a new component which uses regex matching to scan for services.
- OS: `Ubuntu`

Add services and regex matching to the service scanner

---

web/static/css/style.css
web/static/index.html
web/static/js/main.js

- I have made changes to the navbar to align the buttons properly in every view. For doing that, I have changed the structure of how navbar was written.
- I have made changes to the cards in the results view to remove the &nbsp as I think it is a bad practice and have aligned the buttons above the cards perfectly.
- I have made changes to the crawler view aligning the search bar and the buttons properly for every view.
- I have made some grammatical changes: 
- Changing logout to Logout.
I never imagined it will take so much time, but it is done I think. @Ali-Razmjoo, @pradeepjairamani can you please review the PR and let me know if any changes are needed.
In reference to issue #118.
- OS: `Ubuntu`
- Browser: `Firefox Quantum 61.0 (64-bit)`

Make the frontend responsive to most of the phones and tablets

---

lib/scan/subdomain/engine.py

Fixes Issue #202 . This was due to changing of rendering on https://crt.sh. I changed the way data is parsed.
- OS: `Ubuntu`
- Python Version: `2.7`

Fixes Issue #202

---

readme.md

Fixed grammatical errors
- OS: `x`

Fixed some typos

---

lib/payload/password/generator/readme.md

fixed a grammatical error.
- OS: `x`

Fixed typo

---

core/targets.py

Issue: #185 
This PR fixes the bug due to which targets were not properly distinguished.
- OS: `Manjaro`
- OS Version: `4.20`
- Python Version: `3.5`

Fix regex for proper target recognition

---

core/alert.py
core/color.py
core/compatible.py

- Resolves #237, a circular dependency import issue between `core/alert.py` and `core/compatible.py`.
- Improves code quality by removing wildcard imports.
- OS: `Ubuntu`

Resolves Circular Dependency Import

---

core/log.py

Added the CSV export feature. The tool now supports the csv export feature of the shell output.
- OS: `Linux`

Added csv export feature to the tool

---

lib/brute/telnet/engine.py

Fixed #288 
- OS: `Linux`
- OS Version: `ubuntu 18.04`

Fixed telnet_brute issue

---

lib/payload/scanner/kippo_honeypot/engine.py

Fixes #242, and the bugs within the `kippo_honeypot` module.
- OS: `Ubuntu`

Fixing bugs within the kippo_honeypot module

---

core/attack.py
lib/brute/http_form/engine.py
lib/http_fuzzer/engine.py
lib/payload/scanner/header_blind_sqli/engine.py

This PR addresses the following issues:
- This PR address #222 by switching back to pure Python instead of using libraries which cause conflict and problematic backward-compatibility between the two versions.
- `requirements.txt` of this framework marks `requests==2.19.1` as a requirement. However `attack.py` under `core/` uses an outdated version to suppress `InsecureRequestWarning`. This PR addresses the issue by correctly switching the suppress statement to the `urllib3` library.
- OS: `Ubuntu`
- Python Version: `v3.6`

Fixing multiple dependency issues

---

lib/http_fuzzer/engine.py
lib/scan/pma/engine.py

bug fixed. Now pma_scan will work with both python2 and 3

---

lib/scan/wp_user_enum/engine.py

Improved wp_user_enum_scan as suggested in #281 
- OS: `Linux`

Improved wp_user_enum_scan

---

core/get_input.py

fixed wizard issue

---

lib/scan/shodan/engine.py

Fixed #311 
- OS: `Linux`
- Python Version: `3.6.0`

fixed issues in shodan

---

lib/language/messages_en.py
lib/scan/whatcms/engine.py

The monthly quota limit was not handled.
Added that too in the module:
- OS: `Linux`

Improved whatcms_scan

---

.gitignore
Dockerfile
docker-compose.yml

the dockerfile had some errors, also I added docker-compose, follow the documentation here https://github.com/OWASP/Nettacker/wiki/Installation#docker
- OS: `x`

fix dockerfile and add docker-compose

---

core/log.py

Fixed the XSS vulnerability by properly sanatizing the input(response from the server: server header, x-xss-protection header or any other results) where the threat of XSS is present.
- OS: `Linux`

fixed XSS vulnerability in the HTML reports

---

lib/brute/http_basic_auth/engine.py

Fixed the http_basic_auth module.
- OS: `Linux`

Http basic auth brute fix

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Fix minor typos/formatting.
- OS: `Windows`
- OS Version: `10`
- Python Version: `N/A`
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

Issue and PR Template Fixes

---

.github/FUNDING.yml
readme.md

Bring donations info into compliance with OWASP Foundation policy.
- OS: `Windows`
- OS Version: `10`
- Python Version: `N/A`
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

Fix Donation Details

---

lib/scan/wappalyzer/engine.py

fixed keyError in wappalyzer_scan module

---

core/log.py

Fix import and code duplication

---

lib/vuln/CCS_injection/engine.py

Fixed #246 by importing rule
- OS: `Linux`
- Python Version: `3.x`

Fixed issue #246

---

core/alert.py

Fixing the travis build.
- OS: `Linux`

Directory and user agent

---

api/engine.py

Issue #358 is caused by python2 because python2 send raw data to the templating engine without decoding utf-8 that cause UnicodeDecodeError. So, by detecting which version is used by user we can return our index.html
- OS: `Backbox`
- OS Version: `7.1`
- Python Version: `2.7.17`

Api ui bug (UnicodeDecodeError) solved #358

---

lib/scan/subdomain/engine.py

subdomain module enhancements

---

core/targets.py

Also fixed the regex
This PR intends to fix both #185 and #115.
Please let me know what else has to be done in this.
- OS: `Manjaro`
- OS Version: `4.20`
- Python Version: `3.8`

Support for new target_type

---

core/targets.py

lint fix for target.py

---

lib/language/messages_ps.py

fix missed {} in pashto lang

---

lib/payload/password/__init__.py
lib/payload/password/generator/engine.py
lib/payload/password/generator/readme.md

#192 PR has been removed, i had to recreate this.
- OS: `x`

fix password generator library

---

lib/payload/scanner/header_xss/engine.py

Improvements to the headers_xss module

---

lib/transactions/maltego/nettacker_transforms/src/nettacker_transforms/transforms/http_cookie_vuln_scan.py
lib/vuln/http_cookie/__init__.py
lib/vuln/http_cookie/engine.py

fixed #241 
I have added a new module for finding set-cookie header-based vulnerabilities.
- OS: `Linux`
- Python Version: `3.x`

Added Cookie headers related vulnerability module

---

core/targets.py
lib/brute/http_basic_auth/engine.py
lib/vuln/http_cookie/engine.py

fix targets_protocols

---

.github/workflows/CI.yml

run action on PRs

---

lib/vuln/msexchange_cve_2021_26855/engine.py

I have added the module as per #405 
- OS: `Ubuntu`
- OS Version: `20.04`

Add CVE-2021-26855 vuln module

---

core/targets.py

removed debug print(target) messing up the output during the CIDR network scans
- OS: `MacOS`
- OS Version: `Catalina`
- Python Version: `2.7 & 3.6`
This PR closes #407

removed debug print(target) in targets.py

---

database/db.py
database/sqlite_create.py

I think adding the ` 'check_same_thread': False ` attribute resolves the issue
- OS: `Ubuntu`

Fix #388 and some code reformat

---

api/engine.py

Removed Debug print
- OS: `Linux`

removed debug print

---

requirements.txt

added mechanize to requirements file

---

requirements.txt

Fixed #412 
Added rule module to requirements file
- OS: `Linux`

fixed ccs injection import

---

core/config.py
core/load_modules.py
database/db.py
database/postgres_create.py
requirements.txt

This PR adds support for PostgreSQL. It requires an additional package psycopg2 and has been added to the requirements file. 
- OS: `Ubuntu`
- OS Version: `20.04`

Add postgres support for database

---

.github/workflows/CI.yml
config.py

some wafs detect url in user-agent and block, let's remove it from default config.

remove url from user agent

---

api/api_core.py
web/static/js/main.js

After adding new language we should have add it to API as well. also small fix on HTML code

Fix language

---

config.py
core/compatible.py

As we all know, safe is better than sorry. fix for #453

remove unused newrelic api

---

api/engine.py

fixed ssl error

---

core/graph.py
core/utility.py
database/db.py
database/models.py
lib/graph/d3_tree_v1/engine.py
lib/messages/en.yaml
modules/vuln/msexchange_cve_2021_26855.yaml
modules/vuln/vbulletin_cve_2019_16759.yaml
web/static/js/main.js
web/static/report/table_items.html
web/static/report/table_title.html

Hi,
check the csv, html file reports and let me know if they are better now? maybe test some reporting features and make sure its working?
@itsdivyanshjain @aman566  I think code need to be refactored... please feel free to send your commits.
Best, Ali.

use plain text instead of json for events

---

core/targets.py
core/utility.py

bug fix in events and ports

---

core/utility.py

enhacements in the events

---

readme.md

minor change in the readme file.

update readme fix, fix links

---

core/utility.py
lib/messages/en.yaml
web/static/js/main.js

add filter to long contents

---

core/args_loader.py
core/load_modules.py
core/utility.py
lib/messages/en.yaml

sort modules and profiles in cli and webui

---

api/api_core.py
api/engine.py
database/db.py

bug fix in webui while exporting a report, if the type was not HTML, it still shows text/html type in the header and mess up csv and text files.

Fix webui export

---

core/module_protocols/http.py

we could use allow_redirect i missed it.

remove and use allow_redirect instead

---

modules/vuln/cisco_hyperflex _cve_2021_1497.yaml
modules/vuln/citrix_cve_2019_19781.yaml

* add new module
* fix description in a module

add new module cisco CVE 2021 1497

---

modules/vuln/prestashop_cve_2021_37538.yaml

new prestashop_sqli module

---

modules/vuln/tjws_cve_2021_37573.yaml

new tjws_cve module

---

modules/vuln/phpinfo_cve_2021_37704.yaml

new phpinfo_cve

---

modules/vuln/qsan_storage_xss_cve_2021_37216.yaml

new qsan module

---

modules/vuln/puneethreddyhc_sqli_cve_2021_41649.yaml

new puneethreddy cve-41649 module

---

modules/vuln/placeos_cve_2021_41826.yaml

new placeos cve module

---

modules/vuln/novnc_cve_2021_3654.yaml

new novnc cve module

---

modules/vuln/apache_cve_2021_41773.yaml

new apache cve module

---

modules/vuln/apache_cve_2021_41773.yaml
modules/vuln/galera_webtemp_cve_2021_40960.yaml
modules/vuln/wp_plugin_cve_2021_39316.yaml

seems the regexes had issue in python

fix regex - python

---

api/engine.py

Proper error handling when server fails to start
Seamless user experience and proper error handling
@Ali-Razmjoo
Tested on my machine

error handling when server fails to start

---

web/static/index.html
web/static/js/main.js

- OS: `macOS`
- OS Version: `Big Sur`
- Python Version: `3.8.2`

Improvise things in web console

---

core/utility.py
modules/vuln/log4j_cve_2021_44228.yaml

Log4j CVE 2021 44228

---

core/load_modules.py
modules/vuln/log4j_cve_2021_44228.yaml

fix race condition error and sorting steps

---

modules/vuln/log4j_cve_2021_44228.yaml

damn me if see more race conditions in log4j

possible race condition

---

api/api_core.py

solves the issue #534 which is caused by newly added language 'bn'.
- OS: `x`
- Python Version: `3.9.1`

bug534 fix

---

api/engine.py

open index.html by default

---

core/load_modules.py

bug fix in protocol vs actual lib name

---

.github/workflows/publish_docker_image.yml

push new image to dockerhub from master

---

core/load_modules.py
core/socks_proxy.py
core/utility.py

- [ x] The code is Python 3 compatible.
Refactored some code to make it easier to read and understand
- OS: `x`

Small code refactoring

---

core/module_protocols/core_pop3.py
modules/brute/pop3.yaml
modules/brute/pop3s.yaml

Added pop3 brute force

---

Dockerfile

Python docker image update to v3.11.2-slim  - security and stability update
- [x ] My branch is up-to-date with the Upstream master branch.
Python docker image update to v3.11.2-slim
- OS: `MacOs`
- OS Version: `11.7`
- Python Version: `3.11.2`

Update Dockerfile - Python docker image update

---

tests/core/utility.test.py

- OS: `Fedora`
- OS Version: `37`
- Python Version: `3.11.3`

feat: #597 Add unit testing for select_maximum_cpu_core function

---

modules/scan/joomla_version.yaml

added joomla version logging - resolves #706 
added joomla version logging 
- OS: `macOS`
- OS Version: `12.06`

Updated joomla_version_scan module

---

modules/scan/drupal_version.yaml

added version logging and improved regex - resolves #708 
- OS: `macOS`

Updates drupal_version_scan module

---

modules/scan/moveit_version.yaml

New module: moveit_version_scan  - scan for Progress MOVEit instances (closes #710) 
New module: moveit_version_scan  - scan for Progress MOVEit instances as vulnerable versions are being actively exploited by cybercriminals for data breaches and ransomware attacks (May-June-July 2023)
- OS: `macOS`

New module: moveit_version_scan  - scan for Progress MOVEit instances

---

.gitignore

Add vscode workspace files to the .gitignore

Update .gitignore: exclude VSCode workspace files

---

modules/scan/citrix_lastpatcheddate.yaml

New Module: Citrix Gateway Last Patched Date Scan
New Module: Citrix Gateway Last Patched Date Scan
- OS: `macOS`

New Module: Citrix Gateway Last Patched Date Scan

---

modules/vuln/ivanti_epmm_cve_2023_35082.yaml

detect Ivanti EPMM CVE-2023-35082 vulnerability
New Module Ivanti EPMM CVE-2023-35082 Vulnerability Detection (CISA KEV)
- OS: `macOS`

New Module: Ivanti EPMM CVE-2023-35082

---

modules/scan/ivanti_epmm_lastpatcheddate.yaml

New Module: Ivanti EPMM Last Patched Date Scan - shows the last patched date of the target if the target is Ivanti EPMM
New Module: Ivanti EPMM Last Patched Date Scan
- OS: `macOS`

New Module: Ivanti EPMM Last Patched Date Scan

---

Dockerfile

updating Python image to python 3.11.7-slim
updating Python image to python 3.11.7-slim
- OS: `macOS`

Update Dockerfile to use python 3.11.7

---

modules/vuln/teamcity_cve_2024_27198.yaml

Module to detect TeamCity CVE-2024-27198
- OS: `macOS`

Module to detect TeamCity CVE-2024-27198

---

web/static/css/style.css
web/static/index.html
web/static/js/main.js

This PR fixes issue #805 added pagination to web UI for both Crawler and Results page
https://github.com/OWASP/Nettacker/assets/82499435/5e31924d-266e-45fb-8673-49660cac7914
- OS: `x`

[Feature] Added Pagination in webUI 

---

api/api_core.py

- OS: `Arch Linux
- OS Version: `6.6.20-1-lts`
- Python Version: `3.11.7`

Fixed Typo in Docstring

---

Dockerfile

Update Python base image to 3.11.9-slim

Update Python Docker base image to 3.11.9-slim

---

README.md

Updated README.md to use python poetry

Updated README.md to include python poetry

---

.github/workflows/ci_cd.yml

PYPI publish will be moved to a separate workflow

Update ci_cd.yml remove PYPI step

---

docs/README.md

placeholder for new documentation

Created docs folder

---

.readthedocs.yml
docs/API.md
docs/Contributors.md
docs/Developers.md
docs/Events.md
docs/Home.md
docs/Installation.md
docs/Instructions-for-the-OWASP-Bay-Area-tutorial.md
docs/Media.md
docs/Modules.md
docs/Usage.md
docs/index.md
docs/requirements.txt
mkdocs.yml

loading the Wiki pages into docs

Docs initial commit

---

docs/README.md

to include the ReadTheDocs site

docs README.md update

---

README.md

added docs badge to README.md

---

docs/Home.md

fixed broken images in Home page of documentation due to web folder move during refactoring

Update Home.md in docs - fixed broken images

---

nettacker/modules/scan/subdomain.yaml

Defunct services: bufferoverflow, threatminer and threatcrowd - replaced

Updated subdomain.yaml removing defunct services

---

README.md

Added docker-pulls counter badge to README.md

Added docker-pulls counter badge to README.md

---

nettacker/modules/scan/ivanti_ics_lastpatcheddate.yaml

Overlooked YAML indent fix in ivanti_ics_lastpatcheddate.yaml

YAML indent fix in ivanti_ics_lastpatcheddate.yaml

---

.github/workflows/ci_cd.yml

Update CI/CD: trigger PyPI job on tag push

Update CI/CD: trigger PyPI job on tag push

---

docs/Usage.md
nettacker/core/arg_parser.py

adding "-d" as a shortcut for "--skip-service-discovery" + relevant Usage  documentation update

adding "-d" as a shortcut for "--skip-service-discovery" + docs

---

nettacker/modules/scan/ivanti_vtm_version.yaml

new module: ivanti_vtm_version_scan to help find CVE-2024-7593 a

new module: ivanti_vtm_version_scan

---

.github/workflows/ci_cd.yml

Add `merge_group` trigger

---

nettacker/locale/es.yaml

Added Spanish translations for scan comparison (issue  #905 )
- OS: `x`

Added Spanish translations for scan comparison (issue  #905 )

---

docs/Home.md
docs/Installation.md
docs/index.md

Updating the installation doumentation due to new ways to install Nettacker using PYPI,PIPX,Poetry and Docker

Documentation update

---

docs/Installation.md

minor formatting fixes in Installation.md (removed extra tabs and added missing paragraph breaks)

Update Installation.md - minor formatting fixes

---

.github/workflows/ci_cd.yml

Pin runner image version to avoid breaking changes introduced by migration to ubuntu-24.04

Pin runner image OS version

---

nettacker/locale/zh-cn.yaml

Checklist
I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
The code has been thoroughly tested in my local development environment with flake8 and pylint.
The code is Python 3 compatible.
The code follows the PEP8 styling guidelines with 4 spaces indentation.
This Pull Request relates to only one issue or only one feature
I have referenced the corresponding issue number in my commit message
I have added the relevant documentation.
My branch is up-to-date with the Upstream master branch.
Added Chinese translations for scan comparison (issue: https://github.com/OWASP/Nettacker/issues/905 )
Changes proposed in this pull request:
Added Chinese translations for the zh-cn.yaml localization file.
Resolves issue …

Add some ChineseTranslation

---

nettacker/modules/vuln/paloalto_panos_cve_2025_0108.yaml

Adding cisa_kev profile to the  CVE-2025-0108 vulnerability detection module.
The U.S. Cybersecurity and Infrastructure Security Agency (CISA) has just added this CVE-2025-0108 impacting Palo Alto Networks PAN-OS to its Known Exploited Vulnerabilities (KEV) catalog, based on evidence of active exploitation.
Ref:  https://thehackernews.com/2025/02/cisa-adds-palo-alto-networks-and.html
Your PR description goes here.

Update paloalto_panos_cve_2025_0108.yaml added cisa_kev

---

docs/Modules.md
nettacker/modules/vuln/paloalto_panos_cve_2025_0108.yaml
nettacker/modules/vuln/sonicwall_sslvpn_cve_2024_53704.yaml

SonicWALL SSLVPN vulnerability CVE-2024-53704 detection module

adding SonicWALL SSLVPN CVE-2024-53704 module

---

Dockerfile

bumping python base image to 3.11.11
Your PR description goes here.

Update Dockerfile - bump python to 3.11.11

---

nettacker/locale/it.yaml

Checklist
I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
The code has been thoroughly tested in my local development environment with flake8 and pylint.
The code is Python 3 compatible.
The code follows the PEP8 styling guidelines with 4 spaces indentation.
This Pull Request relates to only one issue or only one feature
I have referenced the corresponding issue number in my commit message
I have added the relevant documentation.
My branch is up-to-date with the Upstream master branch.
Added Italian translations for scan comparison (issue: https://github.com/OWASP/Nettacker/issues/905 )
Changes proposed in this pull request:
Added Italian translations for the it.yaml localization file.
Resolves issue …

Add some ItalianTranslation

---

nettacker/lib/payloads/wordlists/admin_wordlist.txt
nettacker/lib/payloads/wordlists/dir_wordlist.txt
nettacker/lib/payloads/wordlists/pma_wordlist.txt
nettacker/lib/payloads/wordlists/wp_plugin_small.txt
nettacker/lib/payloads/wordlists/wp_timethumbs.txt
tests/conftest.py
tests/lib/payloads/test_wordlists.py

Implemented tests for wordlists to ensure no tampering. I have removed duplicates from these lists and conftest wasn't fixed in #863 commit [8a64187](https://github.com/OWASP/Nettacker/commit/8a64187048761414c6e4c9546005f0a14566078c) so removed src/ from nettacker's path.

Implemented tests and removed duplicates for wordlists

---

nettacker/core/lib/telnet.py

Fix the `brute_force` method in `TelnetLibrary` by adding the missing `self` parameter and applying encoding to the username and password to prevent errors.

Fix issues in telnet.py located in core/lib

---

docs/API.md

The API docs have incorrect and missing headers in the post request implementation, leading to issues like #1036. Following from the discussions there, this is to update the relevant parts of the API documentation.

updated relevant parts of the documentation

---

ADOPTERS.md
README.md

Adding ADOPTERS.md encouraging adopters to announce themselves

Adding ADOPTERS.md

---

nettacker/api/engine.py

Security improvements:
* added security headers to API engine responses
* prevented Server header from exposing version info, now it returns just "API"

security improvements

---

nettacker/core/lib/ssh.py
nettacker/core/lib/telnet.py

As specified in title, this PR updates SSH and Telnet client instantiations, respect to their base class.

refactor: use class attribute for SSH and Telnet client instantiation

---

tests/database/test_models.py
tests/database/test_mysql.py
tests/database/test_postgresql.py
tests/database/test_sqlite.py

This PR is to add unittests for database files. It covers mysql.py, postgresql.py, models.py and sqlite.py.

Unittets for database files

---

nettacker/modules/vuln/strict_transport_security.yaml

Updating regex for strict_transport_security_vuln

---

nettacker/locale/id.yaml

Added Indonesian translations for scan comparison (issue: https://github.com/OWASP/Nettacker/issues/905 )
- OS: `Ubuntu`
- OS Version: `22.04.1 LTS`
- Python Version: `3.10.12`

chore: add indonesian translation

---

README.md
docker-compose.yml

Updated README with the updated description, Quick Start commands using docker (updated) and relateed docker-compose command update

Readme update with updated text, docker commands +docker-compose update

---

docs/CodebaseOverview.md
docs/Developers.md

added  OWASP Nettacker Codebase Overview to the docs, to help new contributors find their way around the codebase.

Docs: add Codebase Overview

---

AGENTS.md

Adding AGENTS.md file - new standard file  to provide the context and instructions to help AI coding agents (such as OpenAI Code, Google Jules, Cursor) to work on the project. See https://agents.md

Added AGENTS.md
