core/log.py
lib/brute/ftp/engine.py
lib/brute/smtp/engine.py
lib/brute/ssh/engine.py
lib/scan/dir/engine.py
lib/scan/subdomain/engine.py
lib/scan/tcp_connect_port/engine.py
lib/scan/viewdns_reverse_ip_lookup/engine.py
lib/vuln/heartbleed/engine.py
requirements.txt

Regarding #22 
Created ` __log_into_file(filename, mode, data)` in [core/log.py](https://github.com/avhvr/OWASP-Nettacker/blob/master/core/log.py#L88) 
used [filelock](https://filelock.readthedocs.io/en/latest/) module (works on windows too)
changed blocks of code in following files: 
- lib/brute/smtp/engine.py
- lib/brute/ssh/engine.py
- lib/brute/ftp/engine.py
- lib/vuln/heartbleed/engine.py
- lib/scan/dir/engine.py
- lib/scan/viewdns_reverse_ip_lookup/engine.py
- lib/scan/tcp_connect_port/engine.py
- lib/scan/subdomain/engine.py
Feedback is appreciated
**OS**: `KDE neon LTS`
**OS Version**: `5.8`
**Python Version**: `3.5.2`

added filelock support to avoid collision while writing logs

---

core/log.py

__log_into_file function is creating an error
It's due to the default behaviour of open in Python 3. By default, Python 3 will open files in Text mode, which means that it also has to apply a text decoding, such as utf-8 or ASCII, for every character it reads.
Python will use your locale to determine the most suitable encoding. On OS X and Linux, this is usually UTF-8. On Windows, it'll use an 8-bit character set, such windows-1252, to match the behaviour of Notepad.
so i added encoding with open. this fixed the error.
**OS**: `windows`
**OS Version**: `windows 10`
**Python Version**: `3.6`

windows 10 bug fixed

---

lib/brute/http_form/engine.py

Solved Issue #69.
Make it compatible in Python 2 and 3 to import HTMLParser and http.cookiejar modules.
**OS**: `Linux` and `Mac OS`
**OS Version**: `Linux Ubuntu` and `Mac OS 10.13`
**Python Version**: `2.7` and `3.6`

solve issue #69

---

EXTERNAL_LIBRARIES_LICENSES.md

Added sqlalchemy MIT license to external licenses.
- OS: `Ubuntu`
- Python Version: `2.7`

Add sqlalchemy to the licences

---

EXTERNAL_LIBRARIES_LICENSES.md

I forgot to add the license for intro.js in my pull request. This adds the license of the same.
- OS: `Ubuntu`

Add license for intro.js

---

lib/http_fuzzer/engine.py

Issue : #135 
There were a few code duplication in `lib/http_fuzzer/engine.py`, thus violating the DRY principle. This PR deals with those issues.
`timeout_sec` is by default set to `None`. We need not need to create a separate `if-else` regarding this. We can pass `timeout=timeout_sec` provided `timeout=None` is a valid parameter.
We can generate the request statement dynamically by using `eval` function, this will reduce chances of repeating ourselves.
- OS: `Kali Linux`
- OS Version: `2`
- Python Version: `3.6.6`

Removed code duplication

---

database/db.py

- [_] I have added the relevant documentation.
Fix a typo in host json report resulting in an always empty list returned.
- OS: `Ubuntu`
- Python Version: `3.6.7`

Fix typo in host json report

---

lib/http_fuzzer/engine.py

Added the following user agents: Windows 10-based PC using Edge browser, Chrome OS-based laptop using Chrome browser (Chromebook), Mac OS X-based computer using a Safari browser, Windows 7-based PC using a Chrome browser, Linux-based PC using a Firefox browser
- OS: `Linux`
- Python Version: `3.x`

Added some latest user agents to the list & fixed a typo

---

lib/vuln/XSS_protection/engine.py

Added two different parameters that may also be present in some websites while checking for X-XSS-Protection header. Used regex for report-uri parameter in the header.
- OS: `Linux`

Improved X-XSS-Protection header codebase

---

lib/vuln/clickjacking/engine.py

Completed the clickjacking by adding the CSP header check via frame-ancestors.
- OS: `Linux`

Added frame-ancestors directive to clickjacking module

---

api/api_core.py
api/engine.py
core/args_loader.py
core/config.py
core/config_builder.py
core/parse.py
lib/language/messages_en.py

This is the code for implementing SSL module for API/GUI for nettacker. Solved issue #133.
Command which will run the server up on https:
`python nettacker.py -i google.com --start-api --api-host 127.0.0.1 --api-port 9999`
- OS: `Linux`
- Python Version: `3.x`

SSL implementation for API/GUI

---

lib/brute/ftp/engine.py
lib/brute/http_ntlm/engine.py

scan_id, scan_cmd were missing in ftp_brute.
http_ntlm_brute was having syntax errors. But it is working in python3.x not in python2.x(tested in Ubuntu 18.04)
- OS: `Linux`

ftp_brute, http_ntlm_brute bugs fixed

---

lib/scan/wp_user_enum/engine.py

The wp_user_enum_scan doesn't check for the **/wp-json/wp/v2/users** for more users.
- OS: `Linux`

Added one more method for user enumeration in wp

---

lib/brute/smtp/engine.py

Fixed #327 starttls issue by using ehlo command to check wheather IP supports tls connection or not.
- OS: `Linux`
- Python Version: `3.8`

fixed smtp starttls issue

---

lib/html_log/_log_data.py

Every report generated contains an external asset (css image background) from jackruguile.com.  Removed this asset with no functional changes except Jack no longer receives requests leaking IPs from every report view.
- [] The code has been thoroughly tested in my local development environment with flake8 and pylint.
- [] The code is both Python 2 and Python 3 compatible.
- [] The code follows the PEP8 styling guidelines with 4 spaces indentation.
- [] This Pull Request relates to only one issue or only one feature
* Remove external asset from report css - no visual / functional changes.
- OS: `Linux`
- OS Version: `Debian 10`
- Python Version: `3.7.3`

Remove external ip leak from reports

---

lib/scan/wappalyzer/apps.json

Here when line 174 in engine.py of the module cats = apps[app_name]['cats'] executes return keyerror because key "IIS\\;confidence:50" doesn't exist in app json. 
changes on line 5880 in app.json as "implies": "IIS\\;confidence:50" to "implies": "IIS" . After implementing this i validated the output i get through wappalyzer_scan module with wappalyzer chrome extension.
- OS: `Backbox`
- OS Version: `7.1`
- Python Version: `3.8`

KeyError in wappalyzer_scan module when IIS is discovered error solved #338

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
core/update.py
lib/graph/d3_tree_v1/engine.py
lib/graph/jit_circle_v1/engine.py
lib/language/messages_ar.py
lib/language/messages_de.py
lib/language/messages_el.py
lib/language/messages_en.py
lib/language/messages_es.py
lib/language/messages_fa.py
lib/language/messages_fr.py
lib/language/messages_hi.py
lib/language/messages_hy.py
lib/language/messages_id.py
lib/language/messages_it.py
lib/language/messages_iw.py
lib/language/messages_ja.py
lib/language/messages_ko.py
lib/language/messages_nl.py
lib/language/messages_ps.py
lib/language/messages_ru.py
lib/language/messages_tr.py
lib/language/messages_ur.py
lib/language/messages_vi.py
lib/language/messages_zh-cn.py
lib/vuln/wordpress_dos_cve_2018_6389/engine.py
readme.md
setup.py
web/static/index.html

References in source code to old Github repository are replaced by new OWASP GitHub repository as mentioned in Issue #363 and a bit of code refactoring.  
- OS: `Ubuntu`

Change old hardcoded reference to OWASP repo #363

---

lib/scan/dir/engine.py

Fixed #280 
Tried fixing dir_scan false positives by making a request to arbitary path which for sure gives 404 and storing the Content-Length of it. Using the difflib module, finding the similarity between the original request(From bruteforcing the path) and the request made for 404. If the ratio is greater than 0.95, then consider it as similar and skip it, else consider it
- OS: `Linux`
- Python Version: `3.8`

Fixed some false positives in dir_scan module

---

requirements.txt

it seems it won't support python 2.7 anymore.

Revert "Bump pycurl from 7.43.0.5 to 7.43.0.6"

---

lib/brute/ftp/engine.py
lib/brute/smtp/engine.py
lib/brute/ssh/engine.py
lib/brute/telnet/engine.py

Solved the issue #394. There are many refrences of `isAlive()` attribute in a different file i changed all of them to `is_alive()`. 
- OS: `Backbox`
- OS Version: `7.1`
- Python Version: `3.8.6`

Attribute Error Fixes 

---

requirements.txt

Scapy < 2.4.5 having a bug which leads to issue #398 which is now fixed in latest version 2.4.5 which i added in requirements.txt file. These changes tested on linux environment with below mentioned python versions and it works completely fine.
- OS: `Backbox`
- OS Version: `7.1`
- Python Version: `2.7.18`,`3.8.5`,`3.9.2`,`3.9.4`

fix port_scan module which having scapy bug

---

lib/scan/wp_plugin/wp_plugins_small.py

adding wp-seopress to the wp_plugin_scan module (small list of plugins) due to CVE-2021-34641 which was disclosed on 2021-08-17 (XSS in wp-seopress plugin allows site takeover)

added wp-seopress plugin CVE-2021-34641

---

.github/workflows/CI.yml
config.py
core/args_loader.py
core/load_modules.py
core/module_protocols/socket.py
core/scan_targers.py
core/targets.py
lib/messages/en.yaml
modules/scan/port.yaml

Hi,
I implemented a similar feature we used to have in version 0.0.2 to ignore a port and send requests, e.g., HTTP if the port is not accepting the first request. this will save us a lot of time during a scan. For example, if a host doesn't have port 80 open, it won't keep trying and failing until the loop is finished. So instead, it will ignore the payload(if it's HTTP) (or any other payload such as ssh or whatever).
There is also a new feature if it discovers a known service (such as HTTP) in service discovery and our protocol exists in the framework. It will automatically rewrite and enforce the port and scan that service with relevant payloads. For instance, if there is an HTTP service on port 5000, and default HTTP ports are set as 80 and 443, it will automatically add 5000 (and …

auto service discovery

---

tests/core/utility.test.py

Unit test of the *sort_dictionary* function was created.
- OS: `Fedora 37`
- OS Version: `Linux F680V9.0 6.2.7-200.fc37.x86_64`
- Python Version: `Python 3.11.2`

feat: #597 Add unit testing for sort_dictionary function

---

lib/payloads/wordlists/wp_plugin_small.txt

Ddded miniorange-login-openid to support detection of Wordpress CVE-2023-2982 (CVSS 9.8 Critical) in WordPress Social Login and Register plugin
Added miniorange-login-openid to wp_plugin_small to support detection of miniorange-login-openid Wordpress plugin which has vulnerability (https://github.com/advisories/GHSA-rx5f-42wm-7p9j) [CVE-2023-2982 CVSS 9.8 Critical]
- OS: `MacOS`

Added miniorange-login-openid to wp_plugin_small

---

modules/scan/http_status.yaml

feature #690 - a simple http_status_scan module returns HTTP Status Code - useful for recon
A simple http_status_scan module which returns HTTP Status Code - useful for recon
- OS: `MacOS`

New module: http_status_scan

---

modules/vuln/citrix_cve_2023_24488.yaml

feature #694 - new module to detect Citrix XSS and open redirect CVE-2023-24488 for which a POC was published on 29-Jun-2023
A new module to detect Citrix XSS CVE-2023-24488
- OS: `MacOS`

New module citrix_cve_2023_24488_vuln

---

modules/vuln/x_powered_by.yaml

updated X-Powered-By module to log the header - resolves #702 
updated X-Powered-By module to log the header
- OS: `macOS`

update X-Powered-By header logging

---

modules/vuln/server_version.yaml

added logging of the server header - resolves #704 
Updated server_version_vuln module to log the header
- OS: `macOS`
- OS Version: `12.06`

Updated server_version_vuln module Server header logging

---

modules/vuln/wp_plugin_cve_2023_6875.yaml

I have added a new module for a vuln module https://nvd.nist.gov/vuln/detail/CVE-2023-6875. This makes it possible for unauthenticated attackers to reset the API key used to authenticate to the mailer and view logs, including password reset emails, allowing site takeover.
```
python3 nettacker.py -i <target> -m wp_plugin_cve_2023_6875_vuln
```
- OS: `Pop!_OS 22.04 LTS`
- OS Version: `Linux pop-os 6.6.6-76060606-generic`
- Python Version: `3.10.12`

Added new module, CVE_2023_6875

---

modules/scan/http_html_title.yaml

HTML Title scan module
New HTML Title scan module extracts the contents of the HTML <TITLE> tag on the target server, if present. This helps to identify what application is running on the server and is particularly useful when scanning networks and subdomains
- OS: `macOS`

New Module: HTML Title scan

---

modules/vuln/ivanti_ics_cve_2023_46805.yaml

Ivanti ICS module template fix: replaced hardcoded User-Agent with variable
Ivanti ICS module template fix: replaced hardcoded User-Agent with variable
- OS: `macOS`

Ivanti ICS module fix: replaced hardcoded User-Agent with variable

---

modules/scan/ivanti_ics_lastpatcheddate.yaml

New Module: Ivanti ICS Last Patched Date scan - shows the last patched date of the target if the target is Ivanti ICS 
New Module: Ivanti ICS Last Patched Date scan
- OS: `macOS`

New Module: Ivanti ICS Last Patched Date Scan

---

README.md

fixed broken images which got affected due to refactoring and updated the disclaimer

Update README.md - fixed broken images

---

docs/Modules.md
nettacker/modules/vuln/apache_ofbiz_cve_2024_38856.yaml

The U.S. Cybersecurity and Infrastructure Security Agency (CISA) added the Apache OFBiz open-source enterprise resource planning (ERP) system CVE-2024-38856 to its Known Exploited Vulnerabilities ) catalog, citing evidence of active exploitation in the wild. 
CVE-2024-38856 carries a score of 9.8 out of 10 on the CVSS vulnerability-severity scale, since it allows pre-authentication remote code execution (RCE). CISA's move comes after proof-of-concept (PoC) exploits were made available to the public following the flaw's disclosure in early August 2024

New module: Apache OFBiz CVE-2024-38856 vulnerability

---

.github/workflows/ci_cd.yml
Dockerfile
docker-compose.yml

Suppresses https://github.com/OWASP/Nettacker/pull/748
Optimize docker image:
- streamline COPY/RUN Dockerfile commands
- update docker-compose.yml
- add docker image build tests

Optimize docker image

---

nettacker/modules/scan/wp_plugin.yaml

Minor improvements - added plugin version to regex and fixed overlooked previously copy-pasted text from another module

Updated wp_plugin.yaml

---

nettacker/locale/ar.yaml

Added Arabic translations for ar.yaml file and there was a typo in an old translation (PORT=ميناء) it was translated as an actual port for ships ( Hamburg Port or San Francisco Port for example) but better translation for this is منفذ which What I have modified too. (issue: #905)
- OS: `Kali GNU/Linux Rolling`
- OS Version: `Linux 6.8.11-amd64`
- Python Version: `3.11.9`

Adding Arabic translations for scan comparison (issue: #905)

---

nettacker/core/app.py
nettacker/core/graph.py

ScanID output added to the CLI scan start up and completion messaging and the HTML report footer for the easy identification of the results belonging to a specific scan and for scan comparison purposes

ScanID added to CLI and HTML report for easy identification of results

---

docs/Installation.md

Updated docs to have the correct installation method using 'pip3 install nettacker' command

Update docs Installation.md for 0.4.0

---

nettacker/lib/payloads/wordlists/wp_plugin_small.txt

Added  the-events-calendar to the list as it has Unauthenticated SQL Injection vulnerability (SQLi) CVE-2024-8275

Updated wp_plugin_small.txt with the-events-calendar (CVE-2024-8275)

---

nettacker/lib/payloads/wordlists/wp_plugin_small.txt

Adding litespeed-cache plugin affected by CVE-2024-47374 to the list of WordPress plugins to scan for. Ref: https://thehackernews.com/2024/10/wordpress-litespeed-cache-plugin.html

Adding litespeed-cache to wp_plugin_small.txt

---

nettacker/locale/fr.yaml

- Didn't go through any test (not qualified to do anything but translate)
- Same 
- Same 
- No changes to the syntax, so if the original file follows it then the translation does too
- Translation requested in #905
- OS: `x`

Update fr.yaml with scan comparision messages

---

nettacker/lib/payloads/wordlists/wp_plugin_small.txt

Adding happy-elementor-addons and chart-builder to the wordpress plugin list due to the latest CVEs:  CVE-2024-10538(Stored XSS)  & CVE-2024-10571 (Unauth LFI)

Update wp_plugin_small.txt: chart-builder & happy-elementor-addons

---

nettacker/lib/payloads/wordlists/wp_plugin_small.txt

Adding  'really-simple-ssl' Wordpress plugin to the list of plugins detected by Nettacker to help identify Wordpress sites vulnerable to CVE-2024-10924

Update wp_plugin_small.txt Add: really-simple-ssl

---

nettacker/core/lib/socket.py
nettacker/modules/scan/port.yaml
tests/core/lib/test_socket.py

This PR fixes found open port printing problem in port_scan module output.
it is printing like this
conditions: open_port: - ''
after that fix, it is
conditions: open_port: - '443'

Fixes open port print in port_scan module.

---

nettacker/api/engine.py

Set the authentication cookie's SameSite attribute to Lax by default to mitigate CSRF attacks, particularly during the grace period of Chrome's automatic Lax implementation.
Added input sanitization for the ``report_path_filename`` parameter in the /new/scan endpoint to prevent attempts to overwrite system files.

Added sanitization to report_path_filename and enhanced authentication cookie

---

nettacker/locale/ko.yaml

Checklist
I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
The code has been thoroughly tested in my local development environment with flake8 and pylint.
The code is Python 3 compatible.
The code follows the PEP8 styling guidelines with 4 spaces indentation.
This Pull Request relates to only one issue or only one feature
I have referenced the corresponding issue number in my commit message
I have added the relevant documentation.
My branch is up-to-date with the Upstream master branch.
Added Korean translations for scan comparison (issue: https://github.com/OWASP/Nettacker/issues/905 )
Changes proposed in this pull request:
Added Korean translations for the ko.yaml localization file.
Resolves issue …

Add some KoreanTranslation

---

nettacker/modules/scan/admin.yaml

Following the discussions over at #1004, #1006 and #1007 I have updated the yaml file for admin scan only.

fixed the admin_scan output to include the hit URLs

---

Modules.md
paloalto_panos_cve_2025_0108.yaml

Your PR description goes here.

adding paloalto_panos_cve_2025_0108_vuln module

---

nettacker/modules/scan/port.yaml

The current regex for SSH port matching is correct for matching banners from Ubuntu, Debian, FreeBSD SSH banners, however a lot of services have SSH banners that are like this
`SSH-2.0-ad34f3baf` 
For example, running the following reveals the same for github.com,
`nc -v github.com 22`
Thus, to match these as well, I have updated the regex. 
Future work includes creating NULL probes to capture banners of services that reveal it without any explicit probing (like SSH, FTP) along with the arbitrary probe that is currently defined.

updated regex for SSH scanning to include more matches

---

nettacker/locale/en.yaml

A small patch for en.yaml, currently if password file is not found it exits with a FileNotFound and KeyError. We already have functionality to exit cleanly but the key was not specified in en.yaml, hence doing that.

small patch for en

---

nettacker/locale/it.yaml

Checklist
I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
The code has been thoroughly tested in my local development environment with flake8 and pylint.
The code is Python 3 compatible.
The code follows the PEP8 styling guidelines with 4 spaces indentation.
This Pull Request relates to only one issue or only one feature
I have referenced the corresponding issue number in my commit message
I have added the relevant documentation.
My branch is up-to-date with the Upstream master branch.
Added Italian translations for scan comparison (issue: https://github.com/OWASP/Nettacker/issues/905 )
Changes proposed in this pull request:
Fix the whole Italian translations for the it.yaml localization file.
Resolves issue …

Fix the whole italian Translation file

---

nettacker/modules/scan/pma.yaml
nettacker/modules/scan/wp_plugin.yaml
nettacker/modules/scan/wp_theme.yaml
nettacker/modules/scan/wp_timethumbs.yaml

Your PR description goes here.
added missing url logging

added missing url logging

---

nettacker/core/arg_parser.py
nettacker/locale/en.yaml

In case of incorrect wordlist specified through CLI implemented in PR #1026, Nettacker wasn't exiting cleanly. Hence, added the clean exit part. 

added clean exit for missing wordlists

---

nettacker/core/lib/socket.py
nettacker/core/module.py
nettacker/modules/scan/port.yaml
tests/core/lib/test_socket.py

improvement over #1052. The following changes were made:
- Added response_dependent logging to socket.py
- Updated tests to support the new structure of port.yaml
- Updated module.py to support the new structure for brute attacks 

Implementing logging response_dependent conditions in socket.py

---

nettacker/modules/scan/port.yaml

#1062 added a new regex which used the the global flag (?s) to allow the proceeding '.' to match newlines. Python re needs this to be at the start of the regex and a "|" doesn't count, leading to silent errors. This PR is to move that pattern to the start of the regex string.

fixing telnet regex added in PR1062

---

nettacker/core/lib/ssl.py

This PR fixes the bug found when I ran `make test` on project. The problem is sometimes we cannot get the address info of remote socket (it doesn't matter why). `ssl_version_and_cipher_scan()` didn't handle this and we got error for nothing. New code fixes that by ignoring the exception and keep going on. `make test` output **before** changes:
```
(nettacker-py3.11) root@2cffc506e9ef:/usr/src/owaspnettacker# make test
poetry run pytest
================================================================================================================================================================== test session starts ===================================================================================================================================================================
platform …
```

Handle socket.gaierror when retrieving server certificate

---

nettacker/database/postgresql.py

Postgresql connected a database, and if it doesn't exist, it needs to create one before connecting to it (this was tried in the except block). Previous code was to connect to the same non-existent database and that won't work, instead we can connect to the default `postgres` database and create a new database from there.

fix the create database part of postgresql.py

---

docs/Modules.md
nettacker/modules/scan/adobe_aem_lastpatcheddate.yaml

New module: adobe_aem_lastpatcheddate_scan - Scan the target for Adobe Experience Manager (AEM) and return its last patched date

New module: adobe_aem_lastpatcheddate_scan
